Traceback (most recent call last):
  File "/opt/hostedtoolcache/Python/3.8.17/x64/lib/python3.8/site-packages/jupyter_cache/executors/utils.py", line 58, in single_nb_execution
    executenb(
  File "/opt/hostedtoolcache/Python/3.8.17/x64/lib/python3.8/site-packages/nbclient/client.py", line 1305, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "/opt/hostedtoolcache/Python/3.8.17/x64/lib/python3.8/site-packages/jupyter_core/utils/__init__.py", line 166, in wrapped
    return loop.run_until_complete(inner)
  File "/opt/hostedtoolcache/Python/3.8.17/x64/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
    return future.result()
  File "/opt/hostedtoolcache/Python/3.8.17/x64/lib/python3.8/site-packages/nbclient/client.py", line 705, in async_execute
    await self.async_execute_cell(
  File "/opt/hostedtoolcache/Python/3.8.17/x64/lib/python3.8/site-packages/nbclient/client.py", line 1058, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "/opt/hostedtoolcache/Python/3.8.17/x64/lib/python3.8/site-packages/nbclient/client.py", line 914, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
from jupyterquiz import display_quiz
display_quiz('quiz.json')
------------------


[0;31m---------------------------------------------------------------------------[0m
[0;31mAttributeError[0m                            Traceback (most recent call last)
Cell [0;32mIn[21], line 2[0m
[1;32m      1[0m [38;5;28;01mfrom[39;00m [38;5;21;01mjupyterquiz[39;00m [38;5;28;01mimport[39;00m display_quiz
[0;32m----> 2[0m [43mdisplay_quiz[49m[43m([49m[38;5;124;43m'[39;49m[38;5;124;43mquiz.json[39;49m[38;5;124;43m'[39;49m[43m)[49m

File [0;32m/opt/hostedtoolcache/Python/3.8.17/x64/lib/python3.8/site-packages/jupyterquiz/dynamic.py:126[0m, in [0;36mdisplay_quiz[0;34m(ref, num, shuffle_questions, shuffle_answers, preserve_responses, border_radius, question_alignment, max_width, colors)[0m
[1;32m    124[0m styles[38;5;241m+[39m[38;5;241m=[39m [38;5;124m"[39m[38;5;124m}[39m[38;5;130;01m\n[39;00m[38;5;130;01m\n[39;00m[38;5;124m"[39m
[1;32m    125[0m [38;5;66;03m#print(styles)[39;00m
[0;32m--> 126[0m f [38;5;241m=[39m [43mimportlib[49m[38;5;241;43m.[39;49m[43mresources[49m[38;5;241;43m.[39;49m[43mfiles[49m(package)[38;5;241m.[39mjoinpath([38;5;124m'[39m[38;5;124mstyles.css[39m[38;5;124m'[39m)
[1;32m    127[0m css [38;5;241m=[39m f[38;5;241m.[39mread_bytes()
[1;32m    128[0m styles [38;5;241m+[39m[38;5;241m=[39m css[38;5;241m.[39mdecode([38;5;124m"[39m[38;5;124mutf-8[39m[38;5;124m"[39m)

[0;31mAttributeError[0m: module 'importlib.resources' has no attribute 'files'

